FROM ubuntu:18.04
LABEL version="2.0" maintainer="<André Menezes>menezesbr@gmail.com"

RUN apt-get update -y
RUN apt-get install -y rpl zip unzip git vim curl nano p7zip-full




# RUN apt-get install apache2 php libapache2-mod-php
# RUN apt-get install php-soap php-xml php-curl php-opcache php-gd php-sqlite3 php-mbstring
# 

# RUN a2dismod mpm_event
# RUN a2dismod mpm_worker
# RUN a2enmod  mpm_prefork
# RUN a2enmod  rewrite
# RUN a2enmod  php7.2